### PR TITLE
#7 Fix date conversion

### LINKED ISSUE #7: BigQuery date converted to Exasol VARCHAR(10)
# Situation

When loading a table from BigQuery that contains a DATE, on the Exasol side it results in a `VARCHAR` instead of a `DATE`.

Example:
`DATE` value "09.01.2020" on BigQuery turned to a `VARCHAR(10) UTF8` in Exasol.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #7

### CODE REVIEW

File: src/test/java/com/exasol/adapter/dialects/bigquery/util/IntegrationTestSetup.java [hunk 1]
```diff
@@ -0,0 +1,217 @@
...
+        } else {
+            LOGGER.info("Using local BigQuery setup");
+            return BigQueryTestSetup.createLocalSetup();
+        }
+    }
+
+    public InetSocketAddress makeLocalServiceAvailableInExasol(final int port) {
+        final ServiceAddress serviceAddress = this.exasolTestSetup.makeLocalTcpServiceAccessibleFromDatabase(port);
+        return new InetSocketAddress(serviceAddress.getHostName(), serviceAddress.getPort());
+    }
```
Comment (ckunki) [inline src/test/java/com/exasol/adapter/dialects/bigquery/util/IntegrationTestSetup.java:86]: unused, proposal: delete?

**Review by ckunki — CHANGES_REQUESTED** [review]

**Review by ckunki — CHANGES_REQUESTED** [review]

**Review by ckunki — APPROVED** [review]
