### PR TITLE
#47: Fix Exasol type checks

### LINKED ISSUE #47: Type check of pushdown query fails with newer Exasol versions
Later Exasol versions use stricter type check for pushdown queries. This causes the following error with BigQuery VS in default mode with adapter property `BIGQUERY_ENABLE_IMPORT` set to `false` or missing:
```
Adapter generated invalid pushdown query for virtual table table1739544294440: Data type mismatch in column number 1 (1-indexed). Expected DECIMAL(19,0), but got DECIMAL(1,0). (pushdown query: SELECT * FROM VALUES(1, 1) WHERE false) 
```

### Potential solution
Add cast to expected column type to generated pushdown query in `BigQueryQueryRewriter`.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #47

### CODE REVIEW

File: src/main/java/com/exasol/adapter/dialects/bigquery/BigQueryColumnMetadataReader.java [hunk 1]
```diff
@@ -30,6 +30,12 @@ public DataType mapJdbcType(final JDBCTypeDescription jdbcTypeDescription) {
         if (jdbcTypeDescription.getJdbcType() == Types.TIME) {
```
Comment (skyglass) [inline src/main/java/com/exasol/adapter/dialects/bigquery/BigQueryColumnMetadataReader.java:30]: Is it possible to cover it with enum switch? It would also make sure that all possible values of enum are handled. There would be a compile error if someone would add new enum, so we would always remember to add correspondent handler here.

**Review by skyglass — CHANGES_REQUESTED** [review]
Some minor comments on switch statement and Path builder

File: src/main/java/com/exasol/adapter/dialects/bigquery/BigQueryColumnMetadataReader.java (hunk 1 above)
Comment (kaklakariada) [reply src/main/java/com/exasol/adapter/dialects/bigquery/BigQueryColumnMetadataReader.java:30]: I thought about this. But we don't need to handle all cases here, only two. I feel that `switch` would look strange for only two `case`es.

File: src/test/java/com/exasol/adapter/dialects/bigquery/util/IntegrationTestSetup.java [hunk 2]
```diff
@@ -60,10 +62,11 @@ public static IntegrationTestSetup create(final TestConfig config) {
             System.setProperty("test.udf-logs", "true");
         }
         final BigQueryTestSetup bigQueryTestSetup = createBigQueryTestSetup(config);
+        assertNotNull(bigQueryTestSetup.getClient());
         bigQueryTestSetup.start();
+        final ExasolTestSetup exasolTestSetup = new ExasolTestSetupFactory(
+                Path.of("cloudSetup/generated/testConfig.json")).getTestSetup();
```
[the remark this answers is not in the document]
Comment (kaklakariada) [reply src/test/java/com/exasol/adapter/dialects/bigquery/util/IntegrationTestSetup.java:68]: This will also work under Windows, I used it very often before ;)

**Review by skyglass — APPROVED** [review]
